--- #YAML:1.0
name: Set-String
version: 0.02
version_from: lib/Set/String.pm
license: perl
distribution_type: module
generated_by: Set-String version 0.02
installdirs: site
requires:
  Array::RefElem: 1
  Test::Simple: 0.47
